### ISSUE TITLE
Creating or editing an entry show a input type=file instead of a input type=text 

### ISSUE THREAD

**Issue by setterlee** [mraible/jhipster4-demo#6]
I follow all steps like are descripted in the readme.md, but in my case the modal to create or edit a blog's entry show a input type=file in the content field instead of a type=text. 

I wish to now if that is normal...

Thanks

**Comment by mraible** [comment]
Are you creating entities from the command line or using JDL Studio? If you're using the same .jh file that I did, it's probably because your database doesn't support CLOB. 

If you're generating entities from the command line, when you choose `Blob` for the field type, make sure you select `CLOB (Text Field)`.

<img width="1237" alt="screen shot 2017-04-19 at 5 07 45 pm" src="https://cloud.githubusercontent.com/assets/17892/25206027/dacc4218-2522-11e7-84a7-45a86f34c54a.png">

**Comment by setterlee** [comment]
I used the same .jh described in the tutorial and the same .yo-rc.json.

In that case, the jhipster generate a longblob field.

![screenshot from 2017-04-19 20-53-19](https://cloud.githubusercontent.com/assets/6598795/25207084/8407dad0-2542-11e7-957b-cf8197463309.png)

but if I generate the entity using the command line, the field is generated as a clob

![screenshot from 2017-04-19 20-53-34](https://cloud.githubusercontent.com/assets/6598795/25207103/9e8d17e4-2542-11e7-9035-0837e4e06591.png)

**Comment by mraible** [comment]
Maybe it's a regression? What version of JHipster are you using? I'll try to reproduce.

**Comment by setterlee** [comment]
I'm using JHipster 4.3.0.

Is easy to reproduce... just take the .yo-rc.json and the .jh file of the tutorial and generate the project with JHipster, then generate a new entity with the command line defining a CLOB field... compare both of changelog for liquibase and you'll see the difference..

**Comment by mraible** [comment]
Please try the latest version, updated today: https://github.com/mraible/jhipster4-demo/pull/14
